apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 742895426293.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 742895426293.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 61b6bcd0
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
